### ISSUE TITLE
index value error

### ISSUE THREAD

**Issue by danielemarinazzo** [artipago/travellignWaveEEG#1]
Hi

thanks for this code.

I get an error when running the "inputData" example, namely the one with [channels time trial].

The error is the following

```
Index in position 1 is invalid. Array indices must be positive integers or logical values.

Error in wavesHunter (line 54)
            fwValue= sbj2DFFT(-b(b2)+numberElectrodes+1,b2+ceil(length(fx)/2)+round(f1/dF));

Error in startingFunction (line 39)
        [dataInputNull(ss).logRatio(tt),dataInputNull(ss).bwValue(tt),dataInputNull(ss).bwTempFreq(tt),dataInputNull(ss).bwSpatFreq(tt),dataInputNull(ss).fwValue(tt),dataInputNull(ss).fwTempFreq(tt),dataInputNull(ss).fwSpatFreq(tt)]=wavesHunter(eegInput(ss).data(randperm(size(eegInput(ss).data,1)),:,tt),samplingRate,freqBandFlag,simmetryFlag);
```

And indeed for tt=31 in the inner loop, the first index

`-b(b2)+numberElectrodes+1
`
is equal to zero.

thanks!

**Comment by artipago** [comment]
Hi Daniele,

thanks for your comment! There was indeed an error in the format of the data. In the OSF repository all 72 electrodes (64 + the external ones ) are stored in the file, but wavesHunter.m actually works on the 2D map composed of only 7 electrodes (usually the midline). I added a few lines of code in wavesHunter.m to select those 'midline' electrodes from those dataset, and it now runs correctly on my pc. Please don't hesitate to let me know whether there is any other problem or I missed something.

I also plan to upload very soon an improved version of wavesHunter.m, in which we consider the whole spectrum rather than a single value. We did something similar in figure 3B of [this paper](https://elifesciences.org/articles/59784.pdf), and the results seem much more informative!

Thanks!
